"""
===============================================================================
A Runtime Intelligence and Adaptive Control-Based Communication Management Framework for LoRa Networks (RIACC)
-------------------------------------------------------------------------------
Configuration File

This file contains all global configuration parameters used throughout the
RIACC simulator.

No module in the project should contain hard-coded constants.
Every configurable value must be defined here.

Research Project:
    A Runtime Intelligence and Adaptive Control-Based Communication Management Framework for LoRa Networks (RIACC)

Simulator Version:
    1.0

Author:
    Safeer Shah

Target:
    IEEE Research Simulator

===============================================================================
"""

from pathlib import Path
from enum import Enum
import random
import numpy as np


# =============================================================================
# PROJECT INFORMATION
# =============================================================================

PROJECT_NAME = "A Runtime Intelligence and Adaptive Control-Based Communication Management Framework for LoRa Networks"

PROJECT_SHORT_NAME = "RIACC"

SIMULATOR_NAME = "RIACC Research Simulator"

VERSION = "1.0"

AUTHOR = "Safeer Shah"

DESCRIPTION = (
    "A Runtime Intelligence and Adaptive Control-Based Communication Management Framework for LoRa Networks framework implementing "
    "Intelligent Sensor Nodes and an Intelligent Master Node for "
    "priority-aware LoRa communication."
)


# =============================================================================
# DIRECTORY STRUCTURE
# =============================================================================

ROOT_DIR = Path(__file__).resolve().parent

DATASET_DIR = ROOT_DIR / "datasets"

RESULTS_DIR = ROOT_DIR / "results"

GRAPH_DIR = RESULTS_DIR / "graphs"

EXPORT_DIR = RESULTS_DIR / "exports"

LOG_DIR = RESULTS_DIR / "logs"

TEMP_DIR = ROOT_DIR / "temp"


# =============================================================================
# RANDOM SEED
# =============================================================================
# Every protocol must execute using the exact same event sequence to ensure
# statistically fair comparison.
# =============================================================================

RANDOM_SEED = 42

random.seed(RANDOM_SEED)

np.random.seed(RANDOM_SEED)


# =============================================================================
# SIMULATION INFORMATION
# =============================================================================

SIMULATION_NAME = "RIACC_Experiment"

SIMULATION_VERSION = "1.0"

ENABLE_LOGGING = True

ENABLE_DEBUG_MODE = False

ENABLE_PROGRESS_BAR = True


# =============================================================================
# SUPPORTED COMMUNICATION PROTOCOLS
# =============================================================================

class Protocol(Enum):
    """
    Communication protocols supported by the simulator.
    """

    PURE_ALOHA = "Pure ALOHA"

    PURE_ALOHA_RIACC = "Pure ALOHA + RIACC"

    LORAWAN_CLASS_A_ADR = "LoRaWAN Class A"

    LORAWAN_CLASS_A_ADR_RIACC = "LoRaWAN Class A + RIACC"

    LORAWAN_CLASS_B = "LoRaWAN Class B"

    LORAWAN_CLASS_B_RIACC = "LoRaWAN Class B + RIACC"


# =============================================================================
# SENSOR NODE STATES
# =============================================================================

class NodeState(Enum):
    """
    Current operating state of an Intelligent Sensor Node.
    """

    IDLE = "IDLE"

    READY = "READY"

    PROCESSING = "PROCESSING"

    WAIT = "WAIT"

    HOLD = "HOLD"

    TRANSMITTING = "TRANSMITTING"

    RETRY = "RETRY"

    SUCCESS = "SUCCESS"

    FAILED = "FAILED"


# =============================================================================
# MASTER NODE DECISIONS
# =============================================================================

class MasterNodeDecision(Enum):
    """
    Control messages generated by the Intelligent Master Node.
    """

    ACK = "ACK"

    GRANT = "GRANT"

    WAIT = "WAIT"

    HOLD = "HOLD"

    RELEASE = "RELEASE"

    RETRY = "RETRY"

    DROP = "DROP"


# =============================================================================
# EVENT LABELS
# =============================================================================

class EventLabel(Enum):
    """
    Dataset labels.
    """

    NORMAL = 0

    ATTACK = 1


# =============================================================================
# THREAT LEVELS
# =============================================================================

class ThreatLevel(Enum):
    """
    Standardized threat levels used throughout the simulator.
    """

    NORMAL = 0

    LOW = 1

    MEDIUM = 2

    HIGH = 3

    CRITICAL = 4


# =============================================================================
# PRIORITY LEVELS
# =============================================================================

class Priority(Enum):
    """
    Dynamic priority assigned after ATI computation.
    """

    LOW = 1

    MEDIUM = 2

    HIGH = 3

    EMERGENCY = 4


# =============================================================================
# PACKET STATUS
# =============================================================================

class PacketStatus(Enum):
    """
    Packet life-cycle inside the simulator.
    """

    GENERATED = "GENERATED"

    QUEUED = "QUEUED"

    SCHEDULED = "SCHEDULED"

    TRANSMITTED = "TRANSMITTED"

    RECEIVED = "RECEIVED"

    ACKNOWLEDGED = "ACKNOWLEDGED"

    COLLIDED = "COLLIDED"

    DROPPED = "DROPPED"

    EXPIRED = "EXPIRED"


# =============================================================================
# CHANNEL STATUS
# =============================================================================

class ChannelState(Enum):
    """
    Current wireless channel condition.
    """

    IDLE = "IDLE"

    BUSY = "BUSY"

    COLLISION = "COLLISION"

    CONGESTED = "CONGESTED"


# =============================================================================
# LOGGING LEVELS
# =============================================================================

class LogLevel(Enum):
    """
    Logging verbosity.
    """

    INFO = "INFO"

    WARNING = "WARNING"

    ERROR = "ERROR"

    DEBUG = "DEBUG"


# =============================================================================
# FILE FORMATS
# =============================================================================

SUPPORTED_DATASET_FORMATS = [
    ".csv"
]

SUPPORTED_EXPORT_FORMATS = [
    "csv",
    "xlsx",
    "json"
]

# =============================================================================
# DATASET CONFIGURATION
# =============================================================================
# This simulator automatically loads every CSV file placed inside the
# datasets directory. The simulator is therefore independent of the number
# of dataset files available.
# =============================================================================


# -----------------------------------------------------------------------------
# DATASET INFORMATION
# -----------------------------------------------------------------------------

DATASET_NAME = "TON-IoT Network Dataset"

DATASET_DESCRIPTION = (
    "TON-IoT Network Dataset used for adaptive LoRa communication simulation."
)

DATASET_FORMAT = "*.csv"

DATASET_FILES = sorted(DATASET_DIR.glob(DATASET_FORMAT))

TOTAL_DATASET_FILES = len(DATASET_FILES)


# -----------------------------------------------------------------------------
# DATASET LOADING
# -----------------------------------------------------------------------------

AUTO_DISCOVER_DATASETS = True

LOAD_DATASET_IN_CHUNKS = True

CHUNK_SIZE = 100000

LOAD_ALL_DATASETS = True

MERGE_DATASETS = True

SORT_EVENTS_BY_TIMESTAMP = True

RESET_INDEX_AFTER_LOADING = True


# -----------------------------------------------------------------------------
# DATA CLEANING
# -----------------------------------------------------------------------------

REMOVE_DUPLICATES = True

DROP_MISSING_VALUES = True

IGNORE_CORRUPTED_ROWS = True

REMOVE_EMPTY_COLUMNS = True

STRIP_COLUMN_NAMES = True

CONVERT_COLUMN_NAMES_TO_LOWERCASE = True


# -----------------------------------------------------------------------------
# REQUIRED DATASET COLUMNS
# -----------------------------------------------------------------------------

REQUIRED_COLUMNS = [

    "ts",

    "src_ip",

    "dst_ip",

    "proto",

    "service",

    "label",

    "type"

]


# -----------------------------------------------------------------------------
# OPTIONAL DATASET COLUMNS
# -----------------------------------------------------------------------------

OPTIONAL_COLUMNS = [

    "src_port",

    "dst_port",

    "duration",

    "orig_bytes",

    "resp_bytes"

]


# -----------------------------------------------------------------------------
# EVENT PROCESSING
# -----------------------------------------------------------------------------

GENERATE_EVENTS = True

EVENT_TIME_UNIT = "milliseconds"

SORT_EVENTS = True

EVENT_QUEUE_ENABLED = True


# -----------------------------------------------------------------------------
# NODE IDENTIFICATION
# -----------------------------------------------------------------------------

NODE_ID_SOURCE = "src_ip"

DESTINATION_ID_SOURCE = "dst_ip"

AUTO_GENERATE_NODE_IDS = True

NODE_PREFIX = "NODE_"

MASTER_NODE_ID = "MASTER_NODE"


# -----------------------------------------------------------------------------
# PAYLOAD CONFIGURATION
# -----------------------------------------------------------------------------

USE_DATASET_PAYLOAD_SIZE = True

PAYLOAD_SIZE_COLUMN = "orig_bytes"

DEFAULT_PAYLOAD_SIZE = None

# NOTE: Payload size bounds are defined once, under
# "LORA PHYSICAL LAYER CONFIGURATION -> PAYLOAD" (MIN_PAYLOAD_SIZE /
# MAX_PAYLOAD_SIZE), to avoid maintaining two constant pairs with the
# same values.


# -----------------------------------------------------------------------------
# DATASET LABELS
# -----------------------------------------------------------------------------

NORMAL_LABEL = 0

ATTACK_LABEL = 1


# -----------------------------------------------------------------------------
# ATTACK TYPE MAPPING
# -----------------------------------------------------------------------------

ATTACK_MAPPING = {

    "normal": "NORMAL",

    "dos": "HIGH",

    "ddos": "CRITICAL",

    "backdoor": "HIGH",

    "password": "MEDIUM",

    "injection": "CRITICAL",

    "ransomware": "CRITICAL",

    "xss": "MEDIUM",

    "scanning": "LOW",

    "mitm": "HIGH"

}


# -----------------------------------------------------------------------------
# DATA VALIDATION
# -----------------------------------------------------------------------------

VALIDATE_TIMESTAMP = True

VALIDATE_SOURCE_NODE = True

VALIDATE_DESTINATION_NODE = True

VALIDATE_PROTOCOL = True

VALIDATE_LABEL = True

VALIDATE_ATTACK_TYPE = True

SKIP_INVALID_RECORDS = True


# -----------------------------------------------------------------------------
# FEATURE ENGINEERING
# -----------------------------------------------------------------------------

ENABLE_FEATURE_ENGINEERING = True

NORMALIZE_NUMERIC_FEATURES = False

ENCODE_CATEGORICAL_FEATURES = False

REMOVE_UNUSED_COLUMNS = False


# -----------------------------------------------------------------------------
# EVENT FILTERING
# -----------------------------------------------------------------------------

FILTER_NORMAL_EVENTS = False

FILTER_ATTACK_EVENTS = False

MINIMUM_EVENT_TIMESTAMP = None

MAXIMUM_EVENT_TIMESTAMP = None


# -----------------------------------------------------------------------------
# DATASET STATISTICS
# -----------------------------------------------------------------------------

PRINT_DATASET_SUMMARY = True

PRINT_ATTACK_DISTRIBUTION = True

PRINT_NODE_DISTRIBUTION = True

PRINT_PROTOCOL_DISTRIBUTION = True



# =============================================================================
# LORA PHYSICAL LAYER CONFIGURATION
# =============================================================================
# These parameters define the physical layer used by every protocol.
# Pure ALOHA and LoRaWAN Class A use the same radio configuration to ensure
# a fair comparison.
# =============================================================================


# -----------------------------------------------------------------------------
# REGIONAL FREQUENCY PLAN
# -----------------------------------------------------------------------------

FREQUENCY_PLANS = {

    "EU868": 868000000,

    "IN865": 865000000,

    "US915": 915000000,

    "AU915": 915000000

}

ACTIVE_FREQUENCY_PLAN = "IN865"

CARRIER_FREQUENCY = FREQUENCY_PLANS[ACTIVE_FREQUENCY_PLAN]


# -----------------------------------------------------------------------------
# CHANNEL CONFIGURATION
# -----------------------------------------------------------------------------

CHANNEL_BANDWIDTH = 125000          # Hz

CHANNEL_COUNT = 1

CHANNEL_INDEX = 0

CHANNEL_ACCESS_METHOD = "Pure ALOHA"


# -----------------------------------------------------------------------------
# SPREADING FACTOR
# -----------------------------------------------------------------------------

SUPPORTED_SPREADING_FACTORS = [

    7,

    8,

    9,

    10,

    11,

    12

]

DEFAULT_SPREADING_FACTOR = 7

MIN_SPREADING_FACTOR = 7

MAX_SPREADING_FACTOR = 12


# -----------------------------------------------------------------------------
# CODING RATE
# -----------------------------------------------------------------------------

SUPPORTED_CODING_RATES = [

    "4/5",

    "4/6",

    "4/7",

    "4/8"

]

DEFAULT_CODING_RATE = "4/5"


# -----------------------------------------------------------------------------
# TRANSMISSION POWER
# -----------------------------------------------------------------------------

SUPPORTED_TX_POWER = [

    2,

    5,

    8,

    11,

    14,

    17,

    20

]

DEFAULT_TX_POWER = 14

MIN_TX_POWER = 2

MAX_TX_POWER = 20


# -----------------------------------------------------------------------------
# PREAMBLE
# -----------------------------------------------------------------------------

PREAMBLE_LENGTH = 8


# -----------------------------------------------------------------------------
# HEADER MODE
# -----------------------------------------------------------------------------

EXPLICIT_HEADER = True

CRC_ENABLED = True

LOW_DATA_RATE_OPTIMIZATION = True

IQ_INVERSION = False


# -----------------------------------------------------------------------------
# PAYLOAD
# -----------------------------------------------------------------------------

MIN_PAYLOAD_SIZE = 8

MAX_PAYLOAD_SIZE = 222


# -----------------------------------------------------------------------------
# RECEIVER SENSITIVITY (dBm)
# Typical Semtech SX1276 Values
# -----------------------------------------------------------------------------

RECEIVER_SENSITIVITY = {

    7: -123,

    8: -126,

    9: -129,

    10: -132,

    11: -134,

    12: -137

}


# -----------------------------------------------------------------------------
# SNR REQUIREMENT (dB)
# Typical LoRa Demodulation Thresholds
# -----------------------------------------------------------------------------

SNR_THRESHOLD = {

    7: -7.5,

    8: -10,

    9: -12.5,

    10: -15,

    11: -17.5,

    12: -20

}


# -----------------------------------------------------------------------------
# PROPAGATION MODEL
# -----------------------------------------------------------------------------

SPEED_OF_LIGHT = 299792458

PATH_LOSS_MODEL = "Log-Distance"

PATH_LOSS_EXPONENT = 2.7

ENABLE_PATH_LOSS = True

ENABLE_SHADOWING = True

ENABLE_SMALL_SCALE_FADING = False

SHADOWING_STANDARD_DEVIATION = 4.0


# -----------------------------------------------------------------------------
# TIME-ON-AIR
# -----------------------------------------------------------------------------

CALCULATE_TIME_ON_AIR = True

USE_STANDARD_LORAWAN_TOA_MODEL = True


# -----------------------------------------------------------------------------
# COLLISION MODEL
# -----------------------------------------------------------------------------

ENABLE_COLLISION_DETECTION = True

ENABLE_CAPTURE_EFFECT = True

ENABLE_HALF_DUPLEX = True

VULNERABLE_PERIOD_MULTIPLIER = 2.0


# -----------------------------------------------------------------------------
# SIGNAL QUALITY
# -----------------------------------------------------------------------------

GENERATE_RSSI = True

GENERATE_SNR = True

ESTIMATE_LINK_QUALITY = True


# -----------------------------------------------------------------------------
# CHANNEL UTILIZATION
# -----------------------------------------------------------------------------

MEASURE_CHANNEL_UTILIZATION = True

MEASURE_CHANNEL_BUSY_TIME = True

MEASURE_IDLE_TIME = True


# -----------------------------------------------------------------------------
# PACKET RECEPTION
# -----------------------------------------------------------------------------

ENABLE_PACKET_ERROR_RATE = True

ENABLE_PACKET_DROP_MODEL = True

ENABLE_DUPLICATE_PACKET_CHECK = True


# -----------------------------------------------------------------------------
# COMMUNICATION TIMERS
# -----------------------------------------------------------------------------

TRANSMISSION_TIMEOUT = 10.0

RECEPTION_TIMEOUT = 5.0

CHANNEL_BUSY_TIMEOUT = 1.0


# -----------------------------------------------------------------------------
# RANDOM ACCESS
# -----------------------------------------------------------------------------

ENABLE_RANDOM_BACKOFF = True

MIN_RANDOM_BACKOFF = 0.1

MAX_RANDOM_BACKOFF = 2.0


# =============================================================================
# COMMUNICATION PROTOCOL CONFIGURATION
# =============================================================================
# Four communication protocols are evaluated.
#
# 1. Pure ALOHA
# 2. Pure ALOHA + RIACC
# 3. LoRaWAN Class A
# 4. LoRaWAN Class A + RIACC
#
# The MAC protocol remains unchanged.
# RIACC only adds intelligence above the MAC layer.
# =============================================================================


# -----------------------------------------------------------------------------
# DEFAULT PROTOCOL
# -----------------------------------------------------------------------------

DEFAULT_PROTOCOL = Protocol.LORAWAN_CLASS_A_ADR_RIACC


# -----------------------------------------------------------------------------
# PROTOCOL EXECUTION
# -----------------------------------------------------------------------------

RUN_PURE_ALOHA = True

RUN_PURE_ALOHA_RIACC = True

RUN_LORAWAN_CLASS_A_ADR = True

RUN_LORAWAN_CLASS_A_ADR_RIACC = True

RUN_LORAWAN_CLASS_B = True

RUN_LORAWAN_CLASS_B_RIACC = True


# -----------------------------------------------------------------------------
# PURE ALOHA CONFIGURATION
# -----------------------------------------------------------------------------

PURE_ALOHA = {

    "ENABLE_PROTOCOL": True,

    "ALLOW_IMMEDIATE_TRANSMISSION": True,

    "ENABLE_RANDOM_BACKOFF": True,

    "ENABLE_ACK": False,

    "ENABLE_WAIT_MESSAGE": False,

    "ENABLE_HOLD_MESSAGE": False,

    "ENABLE_RELEASE_MESSAGE": False,

    "ENABLE_ADR": False,

    "ENABLE_RIACC": False,

    "MAX_RETRANSMISSIONS": 8,

    "MIN_BACKOFF": 0.1,

    "MAX_BACKOFF": 2.0

}


# -----------------------------------------------------------------------------
# PURE ALOHA + RIACC
# -----------------------------------------------------------------------------

PURE_ALOHA_RIACC = {

    "ENABLE_PROTOCOL": True,

    "ALLOW_IMMEDIATE_TRANSMISSION": False,

    "ENABLE_RANDOM_BACKOFF": False,

    "ENABLE_ACK": True,

    "ENABLE_WAIT_MESSAGE": True,

    "ENABLE_HOLD_MESSAGE": True,

    "ENABLE_RELEASE_MESSAGE": True,

    "ENABLE_ADR": False,

    "ENABLE_RIACC": True,

    "USE_MASTER_NODE": True,

    "USE_INTELLIGENT_SCHEDULER": True,

    "USE_ARBITRATION_ENGINE": True,

    "MAX_RETRANSMISSIONS": 8

}


# -----------------------------------------------------------------------------
# LORAWAN CLASS A
# -----------------------------------------------------------------------------

LORAWAN_CLASS_A_ADR = {

    "ENABLE_PROTOCOL": True,

    "ENABLE_ADR": True,

    "ENABLE_RIACC": False,

    "DEVICE_CLASS": "A",

    "ENABLE_ACK": True,

    "CONFIRMED_UPLINK": True,

    "CONFIRMED_DOWNLINK": True,

    "ENABLE_RX1": True,

    "ENABLE_RX2": True,

    "RX1_DELAY": 1.0,

    "RX2_DELAY": 2.0,

    "ADR_MARGIN": 10,

    "ADR_HISTORY_SIZE": 20,

    "ADR_ACK_LIMIT": 64,

    "ADR_ACK_DELAY": 32,

    "MAX_RETRANSMISSIONS": 8

}


# -----------------------------------------------------------------------------
# LORAWAN CLASS A + RIACC
# -----------------------------------------------------------------------------

LORAWAN_CLASS_A_ADR_RIACC = {

    "ENABLE_PROTOCOL": True,

    "ENABLE_ADR": True,

    "ENABLE_RIACC": True,

    "DEVICE_CLASS": "A",

    "ENABLE_ACK": True,

    "ENABLE_WAIT_MESSAGE": True,

    "ENABLE_HOLD_MESSAGE": True,

    "ENABLE_RELEASE_MESSAGE": True,

    "ENABLE_RX1": True,

    "ENABLE_RX2": True,

    "RX1_DELAY": 1.0,

    "RX2_DELAY": 2.0,

    "ADR_MARGIN": 10,

    "ADR_HISTORY_SIZE": 20,

    "ADR_ACK_LIMIT": 64,

    "ADR_ACK_DELAY": 32,

    "USE_MASTER_NODE": True,

    "USE_INTELLIGENT_NODE": True,

    "USE_INTELLIGENT_SCHEDULER": True,

    "USE_ARBITRATION_ENGINE": True,

    "USE_ADAPTIVE_THREAT_INDEX": True,

    "USE_DYNAMIC_PRIORITY": True,

    "USE_BURST_DETECTION": True,

    "USE_ENERGY_MODEL": True,

    "MAX_RETRANSMISSIONS": 8

}


# -----------------------------------------------------------------------------
# LORAWAN CLASS B
# -----------------------------------------------------------------------------
# Standard LoRaWAN Class B uses periodic beacon-synchronized ping slots.
# Beacon period: 128 seconds (LoRaWAN 1.0.3 spec)
# Ping slot period: 1.0 second (periodicity = 7: 128 slots per beacon)
# Channels: 865.0625, 865.4025, 866.4850 MHz (3 standard LoRaWAN IN865 sub-bands)
# SF: Distance / path-loss based (SF7-SF12) — no ADR, no gateway control
# -----------------------------------------------------------------------------

LORAWAN_CLASS_B = {

    "ENABLE_PROTOCOL": True,

    "ENABLE_ADR": False,

    "ENABLE_RIACC": False,

    "DEVICE_CLASS": "B",

    "ENABLE_ACK": True,

    "BEACON_PERIOD": 128.0,          # Seconds — LoRaWAN spec mandatory

    "PING_SLOT_PERIOD": 1.0,         # Seconds — 1 ping slot per second (periodicity=7)

    "ENABLE_RX1": False,             # Class B uses Ping Slots instead of RX1/RX2

    "ENABLE_RX2": False,

    "MAX_RETRANSMISSIONS": 8

}


# -----------------------------------------------------------------------------
# LORAWAN CLASS B + RIACC
# -----------------------------------------------------------------------------
# RIACC piggybacks on Class B ping slots:
# - Gateway broadcasts GNTS threat score in standard beacon downlink
# - RIACC arbitrates WHICH ping slot the node uses (time control)
# - RIACC assigns optimal channel within Class B's 3 sub-bands
# - RIACC assigns optimal SF via grant.assigned_sf (gateway-controlled)
# - Emergency: bypass ping slot wait, immediate SF7 on 866.4 MHz fast-path
# -----------------------------------------------------------------------------

LORAWAN_CLASS_B_RIACC = {

    "ENABLE_PROTOCOL": True,

    "ENABLE_ADR": False,

    "ENABLE_RIACC": True,

    "DEVICE_CLASS": "B",

    "ENABLE_ACK": True,

    "BEACON_PERIOD": 128.0,          # Seconds — same as baseline Class B

    "PING_SLOT_PERIOD": 1.0,         # Seconds — RIACC arbitrates within these slots

    "ENABLE_WAIT_MESSAGE": True,

    "ENABLE_HOLD_MESSAGE": True,

    "ENABLE_RELEASE_MESSAGE": True,

    "USE_MASTER_NODE": True,

    "USE_INTELLIGENT_NODE": True,

    "USE_INTELLIGENT_SCHEDULER": True,

    "USE_ARBITRATION_ENGINE": True,

    "USE_ADAPTIVE_THREAT_INDEX": True,

    "USE_DYNAMIC_PRIORITY": True,

    "USE_BURST_DETECTION": True,

    "USE_ENERGY_MODEL": True,

    "MAX_RETRANSMISSIONS": 8

}


# =============================================================================
# LORAWAN ADR PARAMETERS
# =============================================================================

ADR_ENABLED = True

ADR_HISTORY_WINDOW = 20

ADR_MARGIN = 10

ADR_STEP_SIZE = 3

ADR_MIN_DATA_RATE = 0

ADR_MAX_DATA_RATE = 5

ADR_DEFAULT_DATA_RATE = 0

ADR_DEFAULT_SPREADING_FACTOR = 7

ADR_DEFAULT_TX_POWER = 14

ADR_MIN_TX_POWER = 2

ADR_MAX_TX_POWER = 20


# =============================================================================
# RECEIVE WINDOWS
# =============================================================================

RX1_ENABLED = True

RX2_ENABLED = True

RX1_DELAY = 1.0

RX2_DELAY = 2.0


# =============================================================================
# ACKNOWLEDGEMENT
# =============================================================================

ACK_ENABLED = True

ACK_TIMEOUT = 2.0

CONFIRMED_MESSAGES = True

UNCONFIRMED_MESSAGES = True


# =============================================================================
# RETRANSMISSION
# =============================================================================

ENABLE_RETRANSMISSION = True

MAX_RETRANSMISSIONS = 8

RETRANSMISSION_DELAY = 1.0


# =============================================================================
# DUTY CYCLE
# =============================================================================

ENABLE_DUTY_CYCLE = True

DUTY_CYCLE_PERCENTAGE = 1.0


# =============================================================================
# EXPERIMENT EXECUTION
# =============================================================================

EXECUTE_PROTOCOLS = [

    Protocol.PURE_ALOHA,

    Protocol.PURE_ALOHA_RIACC,

    Protocol.LORAWAN_CLASS_A_ADR,

    Protocol.LORAWAN_CLASS_A_ADR_RIACC

]


# =============================================================================
# ENERGY MODEL CONFIGURATION
# =============================================================================
# Energy consumption is calculated using a radio energy model based on
# LoRa transceiver characteristics. The simulator tracks remaining energy
# during transmission, reception, processing and idle operation.
# =============================================================================


# -----------------------------------------------------------------------------
# ENERGY MODEL
# -----------------------------------------------------------------------------

ENABLE_ENERGY_MODEL = True

INITIAL_BATTERY_PERCENTAGE = 100.0

BATTERY_CAPACITY_mAh = 2400.0

SUPPLY_VOLTAGE = 3.3


# -----------------------------------------------------------------------------
# CURRENT CONSUMPTION (mA)
# -----------------------------------------------------------------------------

TX_CURRENT = {

    2: 22,

    5: 28,

    8: 31,

    11: 34,

    14: 44,

    17: 87,

    20: 120

}

RX_CURRENT = 12.0

IDLE_CURRENT = 0.0015

SLEEP_CURRENT = 0.0002

CPU_CURRENT = 8.0


# -----------------------------------------------------------------------------
# NODE OPERATING STATES
# -----------------------------------------------------------------------------

ENABLE_SLEEP_MODE = True

ENABLE_IDLE_MODE = True

ENABLE_PROCESSING_ENERGY = True

ENABLE_RECEIVING_ENERGY = True

ENABLE_TRANSMISSION_ENERGY = True


# -----------------------------------------------------------------------------
# ENERGY ACCOUNTING
# -----------------------------------------------------------------------------

UPDATE_ENERGY_AFTER_TX = True

UPDATE_ENERGY_AFTER_RX = True

UPDATE_ENERGY_AFTER_PROCESSING = True

UPDATE_ENERGY_AFTER_IDLE = True

UPDATE_ENERGY_AFTER_SLEEP = True


# -----------------------------------------------------------------------------
# BATTERY STATUS LEVELS
# -----------------------------------------------------------------------------

BATTERY_FULL = 100.0

BATTERY_HIGH = 75.0

BATTERY_MEDIUM = 50.0

BATTERY_LOW = 25.0

BATTERY_CRITICAL = 10.0

BATTERY_EMPTY = 0.0


# -----------------------------------------------------------------------------
# LOW BATTERY POLICIES
# -----------------------------------------------------------------------------

ENABLE_LOW_BATTERY_WARNING = True

ENABLE_CRITICAL_BATTERY_WARNING = True

ALLOW_TRANSMISSION_AT_LOW_BATTERY = True

ALLOW_TRANSMISSION_AT_CRITICAL_BATTERY = False


# -----------------------------------------------------------------------------
# ENERGY STATISTICS
# -----------------------------------------------------------------------------

TRACK_NODE_ENERGY = True

TRACK_NETWORK_ENERGY = True

TRACK_TRANSMISSION_ENERGY = True

TRACK_RECEIVING_ENERGY = True

TRACK_PROCESSING_ENERGY = True

TRACK_IDLE_ENERGY = True

TRACK_SLEEP_ENERGY = True


# -----------------------------------------------------------------------------
# NETWORK LIFETIME
# -----------------------------------------------------------------------------

CALCULATE_NETWORK_LIFETIME = True

NETWORK_DEAD_THRESHOLD = 10.0

FIRST_NODE_DEAD = True

HALF_NODES_DEAD = True

LAST_NODE_DEAD = True


# =============================================================================
# RIACC CONFIGURATION
# =============================================================================
# This section defines the configuration parameters used by the
# A Runtime Intelligence and Adaptive Control-Based Communication Management Framework for LoRa Networks (RIACC) framework.
#
# Three-stage Intelligent Decision Process:
#
# Stage 1 : Intelligent Sensor Node
#           - Burst Detection
#           - Adaptive Threat Index (ATI)
#
# Stage 2 : Node Arbitration
#           - Adaptive Priority
#           - Transmission Request Score
#
# Stage 3 : Intelligent Master Node
#           - Network Monitoring
#           - Scheduling
#           - ACK / WAIT / HOLD / RELEASE
# =============================================================================


# -----------------------------------------------------------------------------
# GLOBAL RIACC
# -----------------------------------------------------------------------------

ENABLE_RIACC = True

ENABLE_INTELLIGENT_SENSOR_NODE = True

ENABLE_INTELLIGENT_MASTER_NODE = True


# -----------------------------------------------------------------------------
# STAGE 1 : BURST DETECTION
# -----------------------------------------------------------------------------

ENABLE_BURST_DETECTION = True

BURST_WINDOW_SIZE = 10

BURST_THRESHOLD = 5

MAX_BURST_SCORE = 100.0


# -----------------------------------------------------------------------------
# STAGE 1 : ADAPTIVE THREAT INDEX (ATI)
# -----------------------------------------------------------------------------

ENABLE_ATI = True

ATI_MIN = 0.0

ATI_MAX = 100.0

ATI_HIGH_THRESHOLD = 80.0

ATI_MEDIUM_THRESHOLD = 60.0

ATI_LOW_THRESHOLD = 40.0


# ATI Weight Configuration
ATI_THREAT_WEIGHT = 0.40

ATI_BURST_WEIGHT = 0.30

ATI_ENERGY_WEIGHT = 0.20

ATI_EVENT_WEIGHT = 0.10


# -----------------------------------------------------------------------------
# STAGE 2 : NODE ARBITRATION
# -----------------------------------------------------------------------------

ENABLE_NODE_ARBITRATION = True

ARBITRATION_SCORE_MIN = 0.0

ARBITRATION_SCORE_MAX = 100.0


# Arbitration Weights

ARBITRATION_ATI_WEIGHT = 0.50

ARBITRATION_WAIT_WEIGHT = 0.20

ARBITRATION_RETRY_WEIGHT = 0.15

ARBITRATION_ACK_WEIGHT = 0.15

# -----------------------------------------------------------------------------
# TRANSMISSION DECISION
# -----------------------------------------------------------------------------

TRANSMISSION_THRESHOLD = 50.0


# ============================================================================
# SENSOR NODE RUNTIME
# ============================================================================

MAX_RETRY_COUNT = 3

MAX_LOCAL_QUEUE_SIZE = 10

ACK_TIMEOUT_SECONDS = 2.0

DUPLICATE_EVENT_WINDOW = 2.0

EVENT_EXPIRY_SECONDS = 30.0


# ============================================================================
# QUEUE MANAGEMENT
# ============================================================================

STARVATION_TIMEOUT = 15.0

QUEUE_HEALTH_WARNING = 0.80

QUEUE_HEALTH_CRITICAL = 0.95

PRIORITY_BOOST_INCREMENT = 5.0


# -----------------------------------------------------------------------------
# PRIORITY LEVELS
# -----------------------------------------------------------------------------

LOW_PRIORITY_THRESHOLD = 30.0

MEDIUM_PRIORITY_THRESHOLD = 60.0

HIGH_PRIORITY_THRESHOLD = 80.0

EMERGENCY_PRIORITY_THRESHOLD = 95.0


# -----------------------------------------------------------------------------
# STAGE 3 : INTELLIGENT MASTER NODE
# -----------------------------------------------------------------------------

ENABLE_MASTER_NODE_SCHEDULER = True

ENABLE_NETWORK_MONITOR = True

ENABLE_CHANNEL_ESTIMATION = True

ENABLE_DYNAMIC_SCHEDULING = True


# Master Node Scheduler Weights

MASTER_ATI_WEIGHT = 0.40

MASTER_RSSI_WEIGHT = 0.20

MASTER_SNR_WEIGHT = 0.15

MASTER_CONGESTION_WEIGHT = 0.15

MASTER_QUEUE_WEIGHT = 0.10


# -----------------------------------------------------------------------------
# MASTER NODE DECISIONS
# -----------------------------------------------------------------------------

ENABLE_ACK_MESSAGE = True

ENABLE_WAIT_MESSAGE = True

ENABLE_HOLD_MESSAGE = True

ENABLE_RELEASE_MESSAGE = True


WAIT_TIMEOUT = 2.0

HOLD_TIMEOUT = 5.0

RELEASE_TIMEOUT = 1.0


# -----------------------------------------------------------------------------
# QUEUE MANAGEMENT
# -----------------------------------------------------------------------------

ENABLE_PRIORITY_QUEUE = True

QUEUE_CAPACITY = 5000

MAX_QUEUE_WAIT_TIME = 30.0

DROP_EXPIRED_PACKETS = True


# -----------------------------------------------------------------------------
# NETWORK CONGESTION
# -----------------------------------------------------------------------------

ENABLE_CONGESTION_CONTROL = True

LOW_CONGESTION_THRESHOLD = 0.30

MEDIUM_CONGESTION_THRESHOLD = 0.60

HIGH_CONGESTION_THRESHOLD = 0.85


# -----------------------------------------------------------------------------
# PERFORMANCE TRACKING
# -----------------------------------------------------------------------------

TRACK_ATI = True

TRACK_BURST = True

TRACK_PRIORITY = True

TRACK_ARBITRATION = True

TRACK_MASTER_NODE_DECISIONS = True

TRACK_QUEUE_STATISTICS = True

# =============================================================================
# SIMULATION CONFIGURATION
# =============================================================================

SIMULATION_TIME = 3600.0          # seconds

TIME_STEP = 0.001                 # seconds

REAL_TIME_SIMULATION = False

MAX_SENSOR_NODES = 1000

MASTER_NODE_COUNT = 1

ENABLE_MULTITHREADING = False

ENABLE_PARALLEL_PROCESSING = False


# -----------------------------------------------------------------------------
# EVENT QUEUE
# -----------------------------------------------------------------------------

EVENT_QUEUE_SIZE = 100000

PROCESS_EVENTS_CHRONOLOGICALLY = True

ENABLE_EVENT_LOGGING = False


# -----------------------------------------------------------------------------
# PACKET CONFIGURATION
# -----------------------------------------------------------------------------

DEFAULT_PACKET_TTL = 30.0

MAX_PACKET_RETRIES = MAX_RETRANSMISSIONS

PACKET_BUFFER_SIZE = 10000


# -----------------------------------------------------------------------------
# RESULTS CONFIGURATION
# -----------------------------------------------------------------------------

SAVE_RESULTS = True

SAVE_LOGS = True

SAVE_GRAPHS = True

SAVE_STATISTICS = True

SAVE_SIMULATION_CONFIGURATION = True

OVERWRITE_PREVIOUS_RESULTS = False

EXPORT_CSV = True

EXPORT_JSON = True

EXPORT_EXCEL = True


# -----------------------------------------------------------------------------
# GRAPH CONFIGURATION
# -----------------------------------------------------------------------------

GENERATE_ALL_GRAPHS = True

GRAPH_DPI = 300

GRAPH_FORMAT = "png"

GRAPH_STYLE = "default"

SHOW_GRAPHS = False


# -----------------------------------------------------------------------------
# PERFORMANCE METRICS
# -----------------------------------------------------------------------------

CALCULATE_PACKET_DELIVERY_RATIO = True

CALCULATE_PACKET_LOSS = True

CALCULATE_THROUGHPUT = True

CALCULATE_END_TO_END_DELAY = True

CALCULATE_LATENCY = True

CALCULATE_JITTER = True

CALCULATE_COLLISION_RATE = True

CALCULATE_CHANNEL_UTILIZATION = True

CALCULATE_RETRANSMISSIONS = True

CALCULATE_ENERGY_CONSUMPTION = True

CALCULATE_NETWORK_LIFETIME = True

CALCULATE_QUEUE_STATISTICS = True

CALCULATE_ATI_STATISTICS = True

CALCULATE_PRIORITY_STATISTICS = True

CALCULATE_MASTER_NODE_STATISTICS = True


# -----------------------------------------------------------------------------
# RESEARCH VALIDATION
# -----------------------------------------------------------------------------

ENABLE_RESEARCH_VALIDATION = True

COMPARE_PROTOCOLS = True

GENERATE_COMPARISON_TABLES = True

GENERATE_SUMMARY_REPORT = True

VALIDATE_ENERGY_MODEL = True

VALIDATE_ADR_MODEL = True

VALIDATE_RIACC_MODEL = True

VALIDATE_STATISTICS = True


# -----------------------------------------------------------------------------
# EXPERIMENT REPEATABILITY
# -----------------------------------------------------------------------------

NUMBER_OF_EXPERIMENTS = 10

USE_FIXED_RANDOM_SEED = True

REPRODUCIBLE_RESULTS = True


# -----------------------------------------------------------------------------
# DEBUGGING
# -----------------------------------------------------------------------------

ENABLE_ASSERTIONS = True

ENABLE_EXCEPTION_LOGGING = True

PRINT_SIMULATION_PROGRESS = True

PRINT_PROTOCOL_INFORMATION = True

PRINT_FINAL_SUMMARY = True


# -----------------------------------------------------------------------------
# VERSION INFORMATION
# -----------------------------------------------------------------------------

CONFIG_VERSION = "1.0"

LAST_UPDATED = "July 2026"

IEEE_READY = True